sudo: false
language: rust

rust:
    - stable
    - beta

env:
    - BUILD=test
    - BUILD=codegen

install:
      # RemoteStorage testsuite only runs on Rubby 2
    - rvm use 2
     
      # There is no other way. Trusty doesn't have libsodium
    - if [ "$BUILD" = "test" ]; then
          export LIBSODIUM_VERSION=1.0.8;
          wget https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VERSION/libsodium-$LIBSODIUM_VERSION.tar.gz;
          tar xvfz libsodium-$LIBSODIUM_VERSION.tar.gz;
          (cd libsodium-$LIBSODIUM_VERSION && ./configure --prefix=$HOME/installed_libsodium && make && make install);
          export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH;
          export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH;
      fi
    - make install-$BUILD

script:
    - make TMP_DIR=$PWD/tmp $BUILD
    - git diff --exit-code

cache:
    directories:
        - target
        - $HOME/.cargo
        - $HOME/installed_libsodium
